- hosts: all
  pre_tasks:
    - name: apt update
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: "ansible_distribution == 'Ubuntu'"

  roles:
    - { role: system, become: yes }
    - { role: ntp, become: yes }
